### ISSUE TITLE
Fixing bugs with area label team joining

### ISSUE THREAD

**Issue by synicaltests** [zulipbot-testing/synicalsyntax#19]

**Comment by zulipbot-test** [comment]
Congratulations @synicaltests, you successfully joined teams **zulipbot-testing/"area: documentation (user)"**, **zulipbot-testing/"area: emoji"**!

**Comment by zulipbot-test** [comment]
@zulipbot-testing/server-emoji

**Comment by synicaltests** [comment]
@zulipbot remove "bug" "not a label"

**Comment by synicaltests** [comment]
@zulipbot remove "bug" "not a label"

**Comment by synicaltests** [comment]
@zulipbot remove "bug"

**Comment by synicalsyntax** [comment]
@zulipbot remove "duplicate" "bug" "not labe;"

**Comment by synicaltests** [comment]
@zulipbot remove "duplicate" "bug" "not labe;"

**Comment by zulipbot-test** [comment]
**Error:** Label "not labe;" does not exist and was thus not removed from this issue.

**Comment by synicaltests** [comment]
@zulipbot remove "duplicate" "in progress"

**Comment by zulipbot-test** [comment]
**Error:** Label "duplicate" does not exist and was thus not removed from this issue.

**Comment by synicalsyntax** [comment]
@zulipbot remove "question"

**Comment by synicalsyntax** [comment]
@zulipbot remove "question"

**Comment by synicaltests** [comment]
@zulipbot remove "question"
