### ISSUE TITLE
Remove bug

### ISSUE THREAD

**Issue by synicalsyntax** [zulipbot-testing/synicalsyntax#20]
@zulipbot label "bug"

**Comment by synicalsyntax** [comment]
@zulipbot remove "bug"

**Comment by synicalsyntax** [comment]
@zulipbot remove "bug"

**Comment by zulipbot-test** [comment]
**Error:** Label "bug" does not exist and was thus not removed from this issue.

**Comment by synicalsyntax** [comment]
@zulipbot claim

**Comment by synicalsyntax** [comment]
@zulipbot label "bug"

**Comment by synicalsyntax** [comment]
@zulipbot remove "bug" "depr"

**Comment by zulipbot-test** [comment]
**Error:** Label "depr" does not exist and was thus not removed from this issue.

**Comment by synicalsyntax** [comment]
@zulipbot abandon

**Comment by synicalsyntax** [comment]
@zulipbot label "not label" "not"

**Comment by zulipbot-test** [comment]
**Error:** Labels "not label", "not" do not exist and were thus not added to this issue.

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-hotkeys, @zulipbot-testing/server-misc members, this issue was labeled with the **area: hotkeys**, **area: misc**, **area: topics** labels, so you may want to check it out!
