### ISSUE TITLE
Test issue area labeling and team mentioning

### ISSUE THREAD

**Issue by synicalsyntax** [zulipbot-testing/synicalsyntax#22]

**Comment by synicalsyntax** [comment]
@zulipbot label "area: documentation (user)" "area: emoji"

**Comment by synicalsyntax** [comment]
@zulipbot label "area: documentation (user)" "area: emoji"

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-emoji members, this issue needs your attention!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-user-docs members, this issue needs your attention!

**Comment by synicalsyntax** [comment]
@zulipbot unlabel "area: emoji"

**Comment by synicalsyntax** [comment]
@zulipbot remove "area: emoji"

**Comment by synicalsyntax** [comment]
@zulipbot remove "area: documentation (user)" "area: emoji"

**Comment by synicalsyntax** [comment]
@zulipbot claim

**Comment by synicalsyntax** [comment]
@zulipbot abandon

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-emoji members, this issue needs your attention!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-user-docs members, this issue was labeled with the **area: documentation (user)** label, so you may want to check it out!
