### ISSUE TITLE
Multiple issue payloads through GitHub UI?

### ISSUE THREAD

**Issue by synicalsyntax** [zulipbot-testing/synicalsyntax#29]
test

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-user-docs members, this issue was labeled with the **area: documentation (user)** label, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-emoji members, this issue was labeled with the **area: emoji** label, so you may want to check it out!

**Comment by synicalsyntax** [comment]
test mention

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-user-docs members, this issue was labeled with the **area: documentation (user)** label, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-emoji members, this issue was labeled with the **area: emoji** label, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-emoji members, this issue was labeled with the **area: emoji** label, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-emoji members, this issue was labeled with the **area: emoji** label, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-emoji members, this issue was labeled with the **area: emoji** label, so you may want to check it out!
