### ISSUE TITLE
enforce one command only

### ISSUE THREAD

**Issue by synicalsyntax** [zulipbot-testing/synicalsyntax#42]
@zulipbot claim

@zulipbot label "bug"

**Comment by synicalsyntax** [comment]
@zulipbot claim

@zulipbot label "bug"

**Comment by synicalsyntax** [comment]
@zulipbot claim

@zulipbot label "bug"

**Comment by synicalsyntax** [comment]
@zulipbot label "bug"

@zulipbot remove "bug"

**Comment by synicalsyntax** [comment]
```
@zulipbot abandon
```

**Comment by synicalsyntax** [comment]
`@zulipbot claim`

**Comment by synicalsyntax** [comment]
@zulipbot meme

**Comment by synicalsyntax** [comment]
```
@zulipbot claim
```

**Comment by synicalsyntax** [comment]
```
@zulipbot claim
```

**Comment by zulipbot-test** [comment]
**Error:** Label "bug" does not exist and was thus not removed from this issue.

**Comment by zulipbot-test** [comment]
**Error:** Label "bug" does not exist and was thus not removed from this issue.

**Comment by zulipbot-test** [comment]
**Error:** Label "bug" does not exist and was thus not removed from this issue.

**Comment by zulipbot-test** [comment]
**Error:** Label "bug" does not exist and was thus not removed from this issue.

**Comment by zulipbot-test** [comment]
**Error:** Label "bug" does not exist and was thus not removed from this issue.

**Comment by zulipbot-test** [comment]
**Error:** Label "bug" does not exist and was thus not removed from this issue.

**Comment by synicalsyntax** [comment]
@zulipbot label "add" "bug"

**Comment by zulipbot-test** [comment]
**Error:** Label "add" does not exist and was thus not added to this issue.

**Comment by synicalsyntax** [comment]
@zulipbot remove "bug"

**Comment by synicalsyntax** [comment]
@zulipbot label "bug"

**Comment by zulipbot-test** [comment]
**Error:** Label "bug" does not exist and was thus not removed from this issue.

**Comment by zulipbot-test** [comment]
**Error:** Label "bug" does not exist and was thus not removed from this issue.

**Comment by zulipbot-test** [comment]
**Error:** Label "bug" does not exist and was thus not removed from this issue.

**Comment by zulipbot-test** [comment]
**Error:** Label "bug" does not exist and was thus not removed from this issue.

**Comment by zulipbot-test** [comment]
**Error:** Label "bug" does not exist and was thus not removed from this issue.

**Comment by zulipbot-test** [comment]
**Error:** Label "bug" does not exist and was thus not removed from this issue.

**Comment by zulipbot-test** [comment]
**Error:** Label "bug" does not exist and was thus not removed from this issue.

**Comment by synicalsyntax** [comment]
"do not label" @zulipbot label "bug"

**Comment by synicalsyntax** [comment]
"do not label" @zulipbot remove "bug"

**Comment by synicalsyntax** [comment]
"do not label" @zulipbot label "bug"

**Comment by synicalsyntax** [comment]
"do not label" @zulipbot remove "bug"

**Comment by synicalsyntax** [comment]
"do not label" @zulipbot label "bug"

**Comment by synicalsyntax** [comment]
"do not label" @zulipbot remove "bug"

**Comment by synicalsyntax** [comment]
"do not label" @zulipbot remove "sdfsdf"

**Comment by zulipbot-test** [comment]
**Error:** Label "sdfsdf" does not exist and was thus not removed from this issue.

**Comment by synicalsyntax** [comment]
"do not label" @zulipbot remove "bug"

**Comment by zulipbot-test** [comment]
**Error:** Label "bug" does not exist and was thus not removed from this issue.

**Comment by synicalsyntax** [comment]
hi

**Comment by synicalsyntax** [comment]
"do not label" @zulipbot label "bug"

**Comment by synicalsyntax** [comment]
"do not label" @zulipbot label "bug" "bug go"

**Comment by zulipbot-test** [comment]
**Error:** Label "bug go" does not exist and was thus not added to this issue.

**Comment by zulipbot-test** [comment]
**Error:** Label "bug" already exists and was thus not added again to this issue.

**Comment by synicalsyntax** [comment]
"do not label" @zulipbot remove "bug"

**Comment by zulipbot-test** [comment]
**Error:** Label "meme" does not exist and was thus not added to this issue.
