### ISSUE TITLE
Issue comment/body editing

### ISSUE THREAD

**Issue by synicalsyntax** [zulipbot-testing/synicalsyntax#43]
@zulipbot label "bug"

**Comment by synicalsyntax** [comment]
This issue comment will be edited

**Comment by synicalsyntax** [comment]
@zulipbot claim

**Comment by zulipbot-test** [comment]
**Error:** Label "jh" does not exist and was thus not removed from this issue.

**Comment by zulipbot-test** [comment]
**Error:** Label "jhghhh" does not exist and was thus not added to this issue.

**Comment by synicalsyntax** [comment]
hi

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-emoji members, this issue was labeled with the **area: emoji** label, so you may want to check it out!
