### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by synicalsyntax** [zulipbot-testing/synicalsyntax#66]
@zulipbot-test claim

**Comment by synicaltests** [comment]
@zulipbot claim

**Comment by synicaltests** [comment]
@zulipbot-test claim

**Comment by synicalsyntax** [comment]
@zulipbot-test claim

**Comment by zulipbot-test** [comment]
**ERROR:** You have already claimed to this issue.

**Comment by synicaltests** [comment]
@zulipbot-test claim

**Comment by zulipbot-test** [comment]
Congratulations, @synicaltests, you've successfully claimed your first issue! Contributing to Zulip will (hopefully) be a fun and rewarding experience, and I'm here to help get you off to a good start.

First things first:
* Join me on the [Zulip developers' server](https://chat.zulip.org), to get help, chat about this issue, and meet the other developers.
* Sign the [Dropbox Contributor License Agreement](https://opensource.dropbox.com/cla/), so that Zulip can use your code.
* [Unwatch this repository](https://help.github.com/articles/unwatching-repositories/), so that you don't get 100 emails a day.

As you work on this issue, you'll also want to refer to the [Zulip code contribution guide](http://zulip.readthedocs.io/en/latest/index.html#code-docs), as well as the rest of the developer documentation on that site.


See you on the other side (that is, the pull request side)!

**Comment by synicaltests** [comment]
@zulipbot-test abandon

**Comment by synicaltests** [comment]
@zulipbot-test abandon

**Comment by zulipbot-test** [comment]
**ERROR:** You have not claimed this issue to work on yet.

**Comment by synicalsyntax** [comment]
@zulipbot-test abandon

**Comment by synicalsyntax** [comment]
@zulipbot-test label "i crave death"

**Comment by synicalsyntax** [comment]
@zulipbot-test "here" "where" "the" "world" "is quiet" "bug" "in progress"

**Comment by synicalsyntax** [comment]
@zulipbot-test label "here" "where" "the" "world" "is quiet" "bug" "in progress"

**Comment by zulipbot-test** [comment]
**ERROR:** Labels here, where, the, world, is quiet do not exist and were thus not added to this issue.

**Comment by zulipbot-test** [comment]
**ERROR:** Labels  already exist and were thus not added again to this issue.

**Comment by synicalsyntax** [comment]
@zulipbot-test label "bug" "in progress"

**Comment by zulipbot-test** [comment]
**ERROR:** Labels  do not exist and were thus not added to this issue.

**Comment by zulipbot-test** [comment]
**ERROR:** Labels bug, in progress already exist and were thus not added again to this issue.

**Comment by synicalsyntax** [comment]
@zulipbot-test label "bug" "1+1"

**Comment by zulipbot-test** [comment]
**ERROR:** Label "1+1"" does not exist and was thus not added to this issue.

**Comment by zulipbot-test** [comment]
**ERROR:** Label bug already exists and was thus not added again to this issue.

**Comment by synicalsyntax** [comment]
@zulipbot-test "enhancement" "c'est" "la" "vie" "bug" "in progress"

**Comment by synicalsyntax** [comment]
@zulipbot-test label "enhancement" "c'est" "la" "vie" "bug" "in progress"

**Comment by zulipbot-test** [comment]
**ERROR:** Labels "c'est", "la", "vie"" do not exist and were thus not added to this issue.

**Comment by zulipbot-test** [comment]
**ERROR:** Labels bug", "in progress already exist and were thus not added again to this issue.

**Comment by synicalsyntax** [comment]
@zulipbot-test remove "bug"

**Comment by synicalsyntax** [comment]
@zulipbot-test remove "bug" "not label" "enhancement"

**Comment by zulipbot-test** [comment]
**ERROR:** Labels "bug", "not label" do not exist and were thus not added to this issue.

**Comment by synicalsyntax** [comment]
@zulipbot-test claim

**Comment by synicalsyntax** [comment]
@zulipbot-test claim

**Comment by synicalsyntax** [comment]
@zulipbot-test abandon

**Comment by synicalsyntax** [comment]
@zulipbot-test label "bug"

**Comment by synicalsyntax** [comment]
@zulipbot-test remove "bug"

**Comment by synicalsyntax** [comment]
@zulipbot-test remove "area: misc"

**Comment by synicalsyntax** [comment]
@zulipbot label "area: misc"

**Comment by synicalsyntax** [comment]
@zulipbot-test label "area: misc"

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-misc members, this issue was labeled with the **area: misc** label, so you may want to check it out!

**Comment by synicalsyntax** [comment]
@zulipbot-test claim

**Comment by synicalsyntax** [comment]
@zulipbot-test claim

**Comment by synicalsyntax** [comment]
@zulipbot-test claim

**Comment by synicalsyntax** [comment]
@zulipbot-test claim

**Comment by synicalsyntax** [comment]
@zulipbot-test claim

**Comment by synicalsyntax** [comment]
@zulipbot-test claim

**Comment by synicalsyntax** [comment]
@zulipbot-test claim

**Comment by synicalsyntax** [comment]
@zulipbot-test claim

**Comment by synicalsyntax** [comment]
@zulipbot-test label "bug"

**Comment by synicalsyntax** [comment]
@zulipbot-test claim

**Comment by synicalsyntax** [comment]
@zulipbot-test abandon

**Comment by synicalsyntax** [comment]
@zulipbot-test label "poo" "bug"

**Comment by synicalsyntax** [comment]
@zulipbot-test remove "in progress"

**Comment by synicalsyntax** [comment]
@zulipbot-test label "poo" "bug"

**Comment by zulipbot-test** [comment]
**ERROR:** Label "poo" does not exist and was thus not added to this issue.

**Comment by synicalsyntax** [comment]
@zulipbot-test remove "poo" "bug"

**Comment by zulipbot-test** [comment]
**ERROR:** Label "poo" does not exist and was thus not removed from this issue.

**Comment by synicalsyntax** [comment]
@zulipbot-test remove "poo" "bug"

**Comment by synicalsyntax** [comment]
@zulipbot-test label "bug" "enhancement" "."

**Comment by zulipbot-test** [comment]
**ERROR:** Label "." does not exist and was thus not added to this issue.

**Comment by synicalsyntax** [comment]
@zulipbot-test claim

**Comment by synicalsyntax** [comment]
@zulipbot-test abandon

**Comment by synicalsyntax** [comment]
@zulipbot-test remove "bug" "enhancement"

**Comment by synicalsyntax** [comment]
@zulipbot-test abandon

**Comment by synicalsyntax** [comment]
@zulipbot-test claim @zulipbot test remove "bug" "enhancement" @zulipbot abandon @zulipbot remove "area: misc"

**Comment by synicalsyntax** [comment]
@zulipbot-test test remove "bug" "enhancement" @zulipbot-test abandon @zulipbot-test remove "area: misc"

**Comment by synicalsyntax** [comment]
@zulipbot-test claim

**Comment by synicalsyntax** [comment]
@zulipbot claim
