### ISSUE TITLE
multi assignees removal

### ISSUE THREAD

**Issue by synicalsyntax** [zulipbot-testing/synicalsyntax#81]

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-hotkeys, @zulipbot-testing/server-misc members, this issue was labeled with the **area: hotkeys**, **area: misc** labels, so you may want to check it out!
