### ISSUE TITLE
multi assignees

### ISSUE THREAD

**Issue by synicalsyntax** [zulipbot-testing/synicalsyntax#82]

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by zulipbot-test** [comment]
**ERROR:** This issue has been assigned but is not labeled as being in progress.

**Comment by synicalsyntax** [comment]
@zulipbot-test abandon

**Comment by synicalsyntax** [comment]
@zulipbot-test claim

**Comment by synicalsyntax** [comment]
@zulipbot-test claim

**Comment by synicalsyntax** [comment]
@zulipbot-test claim

**Comment by synicalsyntax** [comment]
@zulipbot-test abandon

**Comment by synicalsyntax** [comment]
@zulipbot-test claim

**Comment by synicalsyntax** [comment]
@zulipbot-test abandon

**Comment by synicalsyntax** [comment]
@zulipbot-test abandon

**Comment by synicalsyntax** [comment]
@zulipbot-test claim
